// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxg42C6wbJvoC93wEJ8pi_AFMlHcJ6E-U',
    appId: '1:54482786240:web:ac07d3ba9d11d5d469da25',
    messagingSenderId: '54482786240',
    projectId: 'chat-app-d1623',
    authDomain: 'chat-app-d1623.firebaseapp.com',
    storageBucket: 'chat-app-d1623.firebasestorage.app',
    measurementId: 'G-1CK8CKDHVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpBkOAj2aPQkJC0JB9ECiZCXZLqP7XWG8',
    appId: '1:54482786240:android:dd814b6d5557c2e669da25',
    messagingSenderId: '54482786240',
    projectId: 'chat-app-d1623',
    storageBucket: 'chat-app-d1623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJpwdnAJ6uo_kXfXNOfO0Zc0Q3NIYw9x0',
    appId: '1:54482786240:ios:0c9409089398d8fb69da25',
    messagingSenderId: '54482786240',
    projectId: 'chat-app-d1623',
    storageBucket: 'chat-app-d1623.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJpwdnAJ6uo_kXfXNOfO0Zc0Q3NIYw9x0',
    appId: '1:54482786240:ios:0c9409089398d8fb69da25',
    messagingSenderId: '54482786240',
    projectId: 'chat-app-d1623',
    storageBucket: 'chat-app-d1623.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxg42C6wbJvoC93wEJ8pi_AFMlHcJ6E-U',
    appId: '1:54482786240:web:5921e30aa8f86b6769da25',
    messagingSenderId: '54482786240',
    projectId: 'chat-app-d1623',
    authDomain: 'chat-app-d1623.firebaseapp.com',
    storageBucket: 'chat-app-d1623.firebasestorage.app',
    measurementId: 'G-9NK1PYX513',
  );
}
